
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: rabbitmq
spec:
  image: docker.io/justin2997/knative-rabbitmq-event-source-worker:lastest # You can change it to your image
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: default
  env:
    - name: RABBITMQ_USER
      value: guest
    - name: RABBITMQ_PASSWORD
      value: guest
    - name: RABBITMQ_PORT
      value: ""
    - name: CONTAINER_SOURCE_NAME
      value: container1
    - name: DEBUG
      value: true
    - name: EXCHANGE_NAME
      value: knative-exchange